owner: scratchsuite
repo: scratchrs
sites:
  - name: ScratchDB by DatOneLefty
    url: https://scratchdb.lefty.one
  - name: ScratchIndexer by DatOneLefty
    url: https://indexer.lefty.one
  - name: my-ocular by Jeffalo
    url: https://my-ocular.jeffalo.net
  - name: FluffyScratch by herohamp
    url: https://fluffyscratch.hampton.pw
    
status-website:
  theme: ocean
  baseUrl: /scratchrs
  logoUrl: https://scratchsuite.github.io/assets/upptime-icon.svg
  name: Scratch Suite
  introTitle: "ScratchSuite"
  introMessage: The Unofficial downtime tracker/pinger for scratcher-made websites like ScratchDB and my-ocular.
  navbar:
    - title: Frontend
      href: /frontend
    - title: Backend
      href: /backend
    - title: Scratcher-Made Websites
      href: /scratchrs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO/

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org) and created for use for everybody at [Scratch](https://scratch.mit.edu). Scratch is developed by the Lifelong Kindergarten Group at the MIT Media Lab. See [scratch.mit.edu](https://scratch.mit.edu). ScratchStatus is not affilated in any way with Scratch. If you want to help improve this, comment on [my profile](https://scratch.mit.edu/users/9gr)
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
